In [1]:
import pandas as pd

In [2]:
mail=pd.read_csv("Spam_Email.csv")

In [3]:
mail

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [4]:
import numpy as np

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
from sklearn.naive_bayes import MultinomialNB

In [8]:
mail.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [9]:
mail.groupby('spam').describe()

text                                                               
     count unique                                                top freq
spam                                                                     
0     4360   4327  Subject: * special notification * aurora versi...    2
1     1368   1368  Subject: naturally irresistible your corporate...    1

In [23]:
x_train,x_test,y_train,y_test = train_test_split(mail.text,mail.spam,test_size=0.2)

In [24]:
corpus = [
    'This is the first document.',#1
    'this Document is second doucment.',#2
    ' and this is third document.' ,#3
    'is this the first document ? ',#4
]

vectorizer = CountVectorizer() 

In [25]:
x = vectorizer.fit_transform(corpus)

In [26]:
print(vectorizer.get_feature_names_out())

['and' 'document' 'doucment' 'first' 'is' 'second' 'the' 'third' 'this']


In [27]:
print(x.toarray())

[[0 1 0 1 1 0 1 0 1]
 [0 1 1 0 1 1 0 0 1]
 [1 1 0 0 1 0 0 1 1]
 [0 1 0 1 1 0 1 0 1]]


In [28]:
vector = CountVectorizer() 
x_train_count = vector.fit_transform(x_train)
x_train_count.toarray()

array([[0, 3, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [29]:
model = MultinomialNB()
model.fit(x_train_count,y_train)

MultinomialNB()

please call pur service repres. on 80801212 between 10AM to 9PM AS You have won guaranteed $1000 cash prize

In [37]:
emails = [
    'you did awesome won 1000 cash prize',
    'you are selected'
]
email_counts = vector.transform(emails)
test = model.predict(email_counts)

for i in test:
    if i==0:
        print('ham email ')
    elif i==1:
        print('spam email')

spam email
ham email 


In [38]:
x_test_count = vector.transform(x_test)

In [40]:
model.score(x_test_count,y_test)

0.993891797556719